language: c

before_install:
 - sudo apt-get install -y linux-headers-$(uname -r)
 - sudo apt-get install -y automake libtool libpcap-dev libglib2.0-dev libjemalloc-dev
 - sudo apt-get install -y build-essential make git hugepages
 - sudo apt-get install -y rats cppcheck flawfinder python-setuptools
 - sudo apt-get install -y bridge-utils
 - sudo apt-get install -y libnuma-dev

 - sudo bash -c "echo 1024 > /proc/sys/vm/nr_hugepages"
 - sudo bash -c "mkdir -p /mnt/huge"
 - sudo bash -c "chmod -R 777 /mnt/huge"
 - sudo bash -c "mount -t hugetlbfs nodev /mnt/huge"
 - sudo apt-get update

script:
 - cd $TRAVIS_BUILD_DIR
 - git config user.name "${GH_USER_NAME}"
 - git config user.email "${USER_MAIL}"
 - export LD="llvm-link"
 - ./configure -p --with-benchmarks --with-examples CC=clang --dpdk-conf x86_64-native-linuxapp-clang
 - ./run_tests.sh
